name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "tests go here"

  # deploy-ios-custom-apps:
  #   needs:
  #     - tests
  #   uses: drspoton/ios-custom-apps/.github/workflows/deploy.yml

  deploy-ios-customer-mobile:
    needs:
      - tests
    uses: drspoton/ios-customer-mobile/.github/workflows/deploy.yml@main

  status:
    needs:
      # - deploy-ios-custom-apps
      - deploy-ios-customer-mobile
    runs-on: macos-11
    steps:
      - name: Show status
        run: |
          echo "Something is no, yes?"
