name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "tests go here"
          # exit $(($RANDOM%2))
  deploy:
    needs:
      - tests
    name: Deploy olo-customer-mobile
    runs-on: macos-11
    strategy:
      matrix:
        repository:
          - drspoton/ios-customer-mobile
          - drspoton/ios-custom-apps
    steps:
      - name: Dispatch olo-customer-mobile
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: my-event
  status:
    needs:
      - deploy
    name: Status
    runs-on: macos-11
    steps:
      - name: Show status
        run: |
          echo "Something is no, yes?"
