name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "tests go here"
          # exit $(($RANDOM%2))
  deploy:
    needs:
      - tests
    name: Deploy olo-customer-mobile
    runs-on: macos-11
    strategy:
      matrix:
        repository:
          - ios-customer-mobile
          - ios-custom-apps
    steps:
      - name: Dispatch workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
         owner: drspoton
         repo: ${{ env.repository }}
         github_token: ${{ secrets.PERSONAL_TOKEN  }}
         workflow_file_name: deploy.yml
         wait_interval: 5
  status:
    needs:
      - deploy
    name: Status
    runs-on: macos-11
    steps:
      - name: Show status
        run: |
          echo "Something is no, yes?"
