name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "tests go here"
          # exit $(($RANDOM%2))
  deploy:
    needs:
      - tests
    name: Deploy olo-customer-mobile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - ios-customer-mobile
          - ios-custom-apps
    uses: "drspoton/${{ matrix.repository }}/.github/workflows/deploy.yml@main"

  status:
    needs:
      - deploy
    name: Status
    runs-on: macos-11
    steps:
      - name: Show status
        run: |
          echo "Something is no, yes?"
