name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "tests go here"
          # exit $(($RANDOM%2))

  deploy-ios-olo-framework:
    needs:
      - tests
    name: Deploy ios-olo-framework
    uses: drspoton/ios-olo-framework/.github/workflows/deploy.yml@main

  deploy-ios-custom-apps:
    needs:
      - tests
    name: Deploy ios-custom-apps
    uses: drspoton/ios-custom-apps/.github/workflows/deploy.yml@main

  status:
    needs:
      - deploy-ios-custom-apps
      - deploy-ios-olo-framework
    name: Status
    runs-on: macos-11
    steps:
      - name: Show status
        run: |
          echo "Something is no, yes?"
