name: Run tests

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

jobs:
  tests:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "tests go here"

  deploy-ios-custom-apps:
    needs:
      - tests
    steps:
      - uses: drspoton/ios-custom-apps/.github/workflows/deploy.yml@main

  deploy-ios-customer-mobile:
    needs:
      - tests
    steps:
      - uses: drspoton/ios-customer-mobile/.github/workflows/deploy.yml@main

  status:
    needs:
      - deploy-ios-custom-apps
      - deploy-ios-customer-mobile
    runs-on: macos-11
    steps:
      - name: Show status
        run: |
          echo "Something is no, yes?"
