name: Run tests

on:
  push:

jobs:
  tests:
    name: Run tests
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "tests go here"
          exit $(($RANDOM%2))
